/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2016 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

\*---------------------------------------------------------------------------*/

#ifndef adiosCloudHeaders_H
#define adiosCloudHeaders_H

#include "Cloud.H"
// #include "CollidingCloud.H"
// #include "DSMCCloud.H"
#include "KinematicCloud.H"
#include "MPPICCloud.H"
// #include "ReactingCloud.H"
// #include "ReactingMultiphaseCloud.H"
// #include "SprayCloud.H"
// #include "ThermoCloud.H"
#include "basicKinematicCloud.H"
#include "basicKinematicCollidingCloud.H"
#include "basicKinematicMPPICCloud.H"
// #include "basicReactingCloud.H"
// #include "basicReactingMultiphaseCloud.H"
// #include "basicSprayCloud.H"
// #include "basicThermoCloud.H"
// #include "coalCloud.H"
// #include "dsmcCloud.H"
#include "indexedParticleCloud.H"
#include "kinematicCloud.H"
// #include "moleculeCloud.H"
#include "passiveParticleCloud.H"
// #include "reactingCloud.H"
// #include "reactingMultiphaseCloud.H"
// #include "sprayCloud.H"
#include "thermoCloud.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
