#!/bin/bash

# Remove decomposition subdirs
/bin/rm -rf processor*

# Remove log files
/bin/rm log.*

# Clear any reconstructed results
#foamCleanTutorials

# And delete mesh
foamCleanPolyMesh

# delete ADIOS output
/bin/rm -rf adiosData/*.bp*

