#!/bin/bash

# Copy base case
[ -d system ] || cp -r $FOAM_TUTORIALS/lagrangian/icoUncoupledKinematicParcelFoam/hopper/hopperInitialState/* ./

# system/adiosDict
[ -f system/adiosDict ] || cp adiosDict system/adiosDict

# system/controlDict needs adios function object
grep "libIOadiosWrite.so" system/controlDict > /dev/null 2>&1 || cat functionObjects >> system/controlDict


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Mesh and run simulation
runApplication blockMesh
runApplication decomposePar
runParallel `getApplication` 4

# Dump last ADIOS file stats to terminal
echo -e "\n\n"
ls -ltr adiosData
echo -e "\n\n"
f=`ls -tr adiosData | tail -1`
echo "-- List content of the last file: ${f}"
bpls adiosData/${f}

