#!/bin/bash

# Remove decomposition subdirs
rm -rf processor*

# Remove log files
rm output/*

# Clear any reconstructed results
#foamCleanTutorials

# And delete mesh
foamCleanPolyMesh

# delete ADIOS output
rm -rf adiosData

