#!/bin/bash

# Create dir for output
mkdir -p output

# Create base mesh and decompose
blockMesh           > output/1-blockMesh.log    2>&1
decomposePar -force > output/2-decomposePar.log 2>&1

# Run analysis
mpirun -np 4 icoFoam -parallel 2>&1 | tee  output/3-icoFoam.log

