#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Copy base case
original=$FOAM_TUTORIALS/heatTransfer/chtMultiRegionFoam/multiRegionHeater
[ -d system ] || cp -r \
    $original/0 \
    $original/constant \
    $original/system \
    .

# system/adiosDict
[ -f system/adiosDict ] || cp adiosDict system/adiosDict

# system/controlDict needs adios function object
grep "libIOadiosWrite.so" system/controlDict > /dev/null 2>&1 || cat functionObjects >> system/controlDict


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite

# remove fluid fields from solid regions (important for post-processing)
for i in heater leftSolid rightSolid
do
    rm -f 0*/$i/{nut,alphat,epsilon,k,U,p_rgh}
done


for i in bottomWater topAir heater leftSolid rightSolid
do
    changeDictionary -region $i > log.changeDictionary.$i 2>&1
done


#-- Run on single processor
#runApplication `getApplication`

# Decompose
runApplication decomposePar -force -allRegions

# Run
runParallel `getApplication`

# Reconstruct
## runApplication reconstructPar -allRegions

## echo
## echo "creating files for paraview post-processing"
## echo
## paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
